name: github Actions

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run JavaScript code
        run: node my-script.js